### PR TITLE
Markdown: Fix UTF8 chars breaking elements

### PR DESCRIPTION
**Pull request by nlepage**
Using UTF8 characters such as emojis in markdown input may create "offsets" in the HTML output and may even break UTF8 characters.

## Example 1
With the following markdown:
```markdown
## test
this is a test `🙂 this is a test` this is a test
```

HTML output is:
```html
<google-codelab-step label="test" duration="0">
  <p>this is a test <code>🙂 this is </code>a test this is a test</p>
</google-codelab-step>
```

## Example 2
With the following markdown:
```markdown
## test
this is a test `this is a test 🙂` this is a test
```

HTML output is:
```html
<google-codelab-step label="test" duration="0">
  <p>this is a test <code>�</code>��� this is a test</p>
</google-codelab-step>
```

## Bug
`splitSpaceRight()` uses a rune index to split a string.

`splitSpaceRight()` and `splitSpaceLeft()` also have their final return reversed.

## Fix
`splitSpaceRight()` now uses a byte index to split the string.

### CODE REVIEW

**Comment by jlandure** [comment]
Any news on this enhancement @jatorre @KeyboardNerd ? 👍

**Review by marcacohen — APPROVED** [review]
thanks!

**Comment by nlepage** [comment]
Just updated this to upstream's master:
- Unicode chars breaking was already fixed
- Kept the tests
- Return params of `splitSpaceRight()` and `splitSpaceLeft()` were still reversed...

@marcacohen I also had opened #367 but don't have time to update it, do whatever you want with it.

**Comment by marcacohen** [comment]
thanks!

**Pull request merged**
