### PR TITLE
Add Vimeo to iframe whitelist

### PR DESCRIPTION
**Pull request by rossbeale**
Small PR to include another common video embed provider.

### CODE REVIEW

**Comment by rossbeale** [comment]
bump...

**Comment by rossbeale** [comment]
@mco-gh - any chance this can be merged?

**Review by mco-gh — APPROVED** [review]
sorry for the delay

**Comment by sweetchowdhury93** [comment]
sweetchowdhury93

**Review by CaramelDelight8491 — APPROVED** [review]

**Pull request merged**
