### PR TITLE
WIP Proto Renderer

### LINKED ISSUE #247: Refactor repo to allow for modular use. Replace Node struct with Protobuf
Tracking issue.

### PR DESCRIPTION
**Pull request by Marcial1234**
Merging the Proto-based Renderer into `master`

Fixes #247

Merging this PR into `master` will add `protoc` as a hard dependency to all package builds (per [`Makefile`](https://github.com/googlecodelabs/tools/pull/293/files#diff-4244a4d1d659f2dda17a55907cbe22cb) change).

There is [documentation](https://github.com/googlecodelabs/tools/pull/293/files#diff-c7e5be55b7e54b4f7bdba7a060405818) on setting it up, but most users rely on built binaries so it shouldn't affect them.

Unware if there's a way to write a "Install the latest dependencies!" messages on a user's next `git pull`, as that'd make for better UX and seamless communication from our end.

### CODE REVIEW

**Comment by Marcial1234** [comment]
The commits on this PR will be squashed to only include links to the merged PRs per #247

**Comment by cassierecher** [comment]
I think all outstanding PRs are merged, yes?

**Comment by Marcial1234** [comment]
@cassierecher All outstanding yes, but the work is not done.
This PR will be merged upon an usage request, or by September 1st. Whichever comes first

**Comment by Marcial1234** [comment]
Closing as change in direction of product.

**Pull request closed without merging**
