### PR TITLE
Update #drawer .steps overflow-x to auto

### LINKED ISSUE #226: Scrolling on Drawer is breaks page if there is large number of steps.
For code labs with more than 12 - 13 steps scrolling is broken:
Screenshot 2019-04-22 at 16 41 33

To reproduce the issue simply view the code lab preview for this code lab doc: 
https://docs.google.com/document/d/1meGkYFAbyuhOd4KpP_e2WTUi6hrmOe0y-oq9ky5dwmw/edit?usp=sharing

The generated URL by the chrome plugin:
https://codelabs-preview.appspot.com/?o=driveui&file_id=1meGkYFAbyuhOd4KpP_e2WTUi6hrmOe0y-oq9ky5dwmw

### PR DESCRIPTION
**Pull request by ablenesi**
Fixes #226

### CODE REVIEW

**Comment by ablenesi** [comment]
@nicolasgarnier Could you take a quick look, this is just a oneliner.

We have a longer codelab with 30+ steps and the navigation issue on the page generated by the Codelab preview is extremely annoying.

**Comment by nicolasgarnier** [comment]
Hey @ablenesi, The change looks OK to me, mainly because I didn't notice any difference on Chrome. Was there an issue on another browser?

Cheers!

**Comment by ablenesi** [comment]
First of all, thank you for your time.

I have tested on Chrome and Safari but the issue appeared only on Chrome.

**Comment by nicolasgarnier** [comment]
Oh sorry, I forgot to check the issue.

The issue is actually already fixed in the codebase. Codelabs went through a redesign which fixed the issue it's just that the previewer tool hasn't yet been updated with the latest version of Codelab elements. I'll close this issue, we should publish an updated on all componants soon.

**Pull request closed without merging**
